### ISSUE TITLE
Graceful degradation?

### ISSUE THREAD

**Issue by synth3tk** [Reedyn/Saga#59] opened 2015-04-29 23:44 UTC
Any plans to make the theme work with JS disabled?

**Comment by Reedyn** [comment] 2015-04-30 04:53
Yes, at the moment it is basically just the feed that doesn't work properly without JS. I cannot give a timeline when it will be done though

**Comment by synth3tk** [comment] 2015-04-30 14:02
Ok, thanks. Was just wondering if it was in the works. Loving the theme otherwise!

**Comment by Reedyn** [comment] 2015-05-03 16:25
Closing this as duplicate of #38

**Closed by Reedyn** 2015-05-03 16:25 UTC
Labels: duplicate, enhancement
