### ISSUE TITLE
Post image not showing on iPad

### ISSUE THREAD

**Issue by Bernjc** [Reedyn/Saga#56] opened 2015-04-20 23:20 UTC
A post image is not showing when you go to the post page. Not sure if this is a ghost problem or a CSS styling problem but only appears to be on the iPad. I've checked on my phone and it looks fine but on an iPad the image looks like it is loading and then goes black. I have not checked a regular browser yet. Other posts seem to be working fine so it could just be this one post which is odd.

Here is the link of where the problem is happening: http://barneycarney.com/2015/04/20/working-on-the-road/

**Comment by Bernjc** [comment] 2015-04-20 23:21
Also, I've tried multiple images and it does the same for all so it doesn't seem to be something with the image size or other image related issues.

**Comment by Reedyn** [comment] 2015-04-21 06:36
I will do some testing :)

**Comment by Reedyn** [comment] 2015-04-21 06:40
Do you have the same issue when the resolution is lower? Currently you have a `3984x2241` size image.

A quick googling suggests that Safari on iPads do have issues displaying images that are that large. Have you tried other browsers?

http://stackoverflow.com/questions/9046143/really-long-background-image-does-not-render-on-ipad-safari

**Comment by Bernjc** [comment] 2015-04-21 15:33
I tried it in multiple browsers and had the same issue even when lower resolutions were used. It works fine now so I'm starting to think it may have been a caching issue or something with Cloudflare not serving the image correctly. I'll keep an eye on it but as of right now I don't think it's a theme issue. Thanks for looking into it!

**Comment by Reedyn** [comment] 2015-05-03 16:16
Closing as the issue is with iPads not handling large images and has nothing to do with the theme.

**Closed by Reedyn** 2015-05-03 16:16 UTC
Labels: bug, wontfix
