### ISSUE TITLE
links, emphasis & italic showing above the rest of the text

### ISSUE THREAD

**Issue by audientmusic** [Reedyn/Saga#73] opened 2015-09-05 10:28 UTC
I love your theme.  I'm running into a few problems, though.  Every link, blood, or italic text is lining up *above* the rest of the text.  I've tried using the ghost markdown as well as straight HTML coding to try to fix it, but I can't get it to work.  Here's an example of what I'm talking about (it's a stupid post.  I'm just practicing...)
http://audientmusic.ghost.io/2015/08/30/aria-giovanni/
Thanks

**Comment by Reedyn** [comment] 2015-09-05 10:29
Closing as it's a duplicate of issue #71

**Closed by Reedyn** 2015-09-05 10:29 UTC
